name: CF优选IP自动更新

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 更新优选IP
        env:
          CFNEW_URL: ${{ secrets.CFNEW_URL }}
        run: |
          python update_ip.py